Repository hmcts/div-respondent-frontend, pull requests merged in 2018-12, with the labels that each got.

#150 Added check on pobox and street for rcd info
  test/unit/helpers/courtInformation.js
  test/unit/steps/respond.test.js
  views/includes/sideMenuCourtDetails.html
Labels: ns:div-rfe-pr-150

#153 add cookie expires
  app.js
  config/default.yml
Labels: ns:div-rfe-pr-153

#154 [PREVIEW] Fixed typo in yarn audit slack warning message
  Jenkinsfile_CNP
Labels: ns:div-rfe-pr-154

#161 DIV-3766 - remove "idam-authentication" (web app) health check
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-rfe-pr-161

#159 DIV-3701 - Set website caching to never/0mb
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-rfe-pr-159

#166 Last minute content fixes
  steps/confirm-defence/ConfirmDefence.content.json
  steps/done/Done.content.json
  steps/progress-bar/ProgressBar.content.json
  test/unit/steps/progressBar.test.js
Labels: ns:div-rfe-pr-166

#165 [PREVIEW] DIV-3787 Apply proxy to idam health-check
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-rfe-pr-165

#164 [PREVIEW] Adding health check for COS & FeesAndPayments services
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-rfe-pr-164

#174 [PREVIEW] Minor changes in readme and use of docker-compose
  .gitignore
  README.md
  docker-compose.yaml
Labels: ns:div-rfe-pr-174

#157 [PREVIEW] DIV-3478 Amed states for handling linking
  const/index.js
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  steps/progress-bar/ProgressBar.step.js
Labels: ns:div-rfe-pr-157

#169 DIV-3812 Revert health-check to original before using the proxy
  middleware/healthcheck.js
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-rfe-pr-169

#172 Done Content appended with HWF link
  steps/done/Done.content.json
  steps/done/Done.html
  test/unit/steps/done.test.js
Labels: ns:div-rfe-pr-172

#171 Remove blank spaces if exists in behaviour details and add extra line…
  steps/review-application/ReviewApplication.html
  steps/review-application/ReviewApplication.step.js
  test/unit/steps/reviewApplication.test.js
Labels: ns:div-rfe-pr-171

#163 Redirect user to DN if user is not respondent
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  middleware/redirectMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer petitionerRedirect.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  resources/mock.json
  steps/respond/Respond.step.js
  test/unit/middleware/redirectMiddleware.test.js
  test/unit/steps/respond.test.js
  test/w3cjs/index.js
  yarn.lock
Labels: ns:div-rfe-pr-163
