Repository hmcts/div-respondent-frontend, pull requests merged in 2018-11, with the labels that each got.

#78 DIV-3528 - temporarily ignored W3C HTML validation tests
  test/w3cjs/index.js
Labels: ns:div-rfe-pr-78

#86 Adding new script that will add environment variables to functional test
  .gitignore
  package.json
  test/e2e/codecept.conf.js
  yarn.lock
Labels: ns:div-rfe-pr-86

#79 DIV-3489 create case for e2e
  .gitignore
  Jenkinsfile_CNP
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  middleware/petitionMiddleware.js
  package.json
  test/e2e/codecept.conf.js
  test/e2e/codecept.smoke.conf.js
  test/e2e/helpers/JSWait.js
  test/e2e/helpers/caseConfigHelper.js
  test/e2e/helpers/caseHelper.js
  test/e2e/helpers/idamConfigHelper.js
  test/e2e/helpers/idamHelper.js
  test/e2e/pages/captureCaseIdAndPin.step.js
  test/e2e/pages/idam.step.js
  test/e2e/paths/happyPath.js
  test/resources/basic-divorce-session.json
  yarn.lock
Labels: ns:div-rfe-pr-79

#92 Add exit page
  config/default.yml
  steps/agree-to-pay-costs/AgreeToPayCosts.content.json
  steps/agree-to-pay-costs/AgreeToPayCosts.html
  steps/agree-to-pay-costs/AgreeToPayCosts.step.js
  steps/end/End.content.json
  steps/end/End.html
  steps/end/End.step.js
  test/e2e/pages/end.step.js
  test/e2e/paths/signout.js
  test/unit/steps/end.test.js
Labels: ns:div-rfe-pr-92

#108 Change additional_host_name to be something other than the default
  infrastructure/aat.tfvars
Labels: ns:div-rfe-pr-108

#104 DIV-3505: Added links and policy pages for cookies, T&Cs and privacy
  config/default.yml
  package.json
  steps/check-your-answers/CheckYourAnswers.html
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  steps/cookies-policy/CookiesPolicy.step.js
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
  steps/privacy-policy/PrivacyPolicy.step.js
  steps/terms-and-conditions/TermsAndConditions.content.json
  steps/terms-and-conditions/TermsAndConditions.html
  steps/terms-and-conditions/TermsAndConditions.step.js
  views/page.njk
  views/question.njk
  yarn.lock
Labels: ns:div-rfe-pr-104

#109 Node modules security patches
  package.json
  test/unit/steps/admitAdultery.test.js
  test/unit/steps/noConsentAreYouSure.test.js
  test/unit/steps/respond.test.js
  yarn.lock
Labels: ns:div-rfe-pr-109

#115 DIV-3494 - fix/enable integration tests
  test/e2e/codecept.conf.js
  test/e2e/paths/happyPath.js
Labels: ns:div-rfe-pr-115

#111 Removed average divorce times table
  steps/respond/Respond.content.json
  steps/respond/Respond.html
Labels: ns:div-rfe-pr-111

#103 remove start page and navigate directly to idam
  config/default.yml
  steps/entry/Entry.step.js
  steps/start/Start.content.json
  steps/start/Start.html
  steps/start/Start.step.js
  test/e2e/pages/start.step.js
  test/e2e/paths/2yrSeparationJourney.js
  test/e2e/paths/5yrSeparationJourney.js
  test/e2e/paths/adulteryJourney.js
  test/e2e/paths/captureCaseAndPin.js
  test/e2e/paths/happyPath.js
  test/e2e/paths/progressBar.js
  test/e2e/smoke/index.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/start.test.js
  yarn.lock
Labels: ns:div-rfe-pr-103

#114 Update to use Family man
  steps/done/Done.html
  test/unit/steps/done.test.js
Labels: ns:div-rfe-pr-114

#113 Privacy policy updated
  steps/cookies-policy/CookiesPolicy.html
  steps/cookies-policy/CookiesPolicy.step.js
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
Labels: ns:div-rfe-pr-113

#137 secure cookies
  app.js
Labels: ns:div-rfe-pr-137

#138 Changed the way court information is displayed to cater for CTSC info…
  middleware/petitionMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  steps/done/Done.content.json
  steps/done/Done.html
  steps/progress-bar/ProgressBar.content.json
  steps/progress-bar/ProgressBar.html
  steps/respond/Respond.content.json
  steps/respond/Respond.html
  test/unit/helpers/courtInformation.js
  test/unit/resources/courtsList.json
  test/unit/steps/done.test.js
  test/unit/steps/progressBar.test.js
  test/unit/steps/respond.test.js
  views/includes/sideMenuCourtDetails.html
  yarn.lock
Labels: ns:div-rfe-pr-138

#142 Incraese code coverage
  steps/privacy-policy/PrivacyPolicy.content.json
  test/unit/services/caseOrchestration.test.js
  test/unit/steps/cookiesPolicy.test.js
  test/unit/steps/privacyPolicy.test.js
  test/unit/steps/termsAndConditions.test.js
Labels: ns:div-rfe-pr-142

#143 Incraese code coverage
  package.json
  test/unit/middleware/feesAndPaymentsMiddleware.test.js
Labels: ns:div-rfe-pr-143
