Repository hmcts/div-respondent-frontend, pull requests merged in 2019-11, with the labels that each got.

#422 python2 and python3 compatibility issue on nightly pipeline
  security.sh
Labels: ns:div-rfe-pr-422

#423 To Add Glue suppression file suggested
  security.sh
Labels: ns:div-rfe-pr-423

#424 configuring glue for false positives
  audit.json
  security.sh
Labels: ns:div-rfe-pr-424

#419 Add api version for helm chart
  charts/div-rfe/Chart.yaml
Labels: ns:div-rfe-pr-419
