Repository hmcts/div-respondent-frontend, pull requests merged in 2019-09, with the labels that each got.

#378 DIV-3877 - enable respondent solicitor feature in AAT
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
Labels: ns:div-rfe-pr-378

#370 DIV-5613 Allow DN Drafted state link
  config/default.yml
  steps/respondent/progress-bar/ProgressBar.config.js
  steps/respondent/progress-bar/ProgressBar.step.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-370

#386 DIV-3877 - enable respondent solicitor feature in AAT tests
  Jenkinsfile_CNP
  config/ci.yml
Labels: ns:div-rfe-pr-386

#387 added wait for Cross Browser Tests
  test/e2e/pages/respondent/hasSolicitor.step.js
  test/e2e/paths/respondent/happyPath.js
Labels: ns:div-rfe-pr-387

#388 add more time for cross Browser
  test/e2e/pages/respondent/agreeToPayCosts.step.js
  test/e2e/pages/respondent/checkYourAnswers.step.js
  test/e2e/pages/respondent/chooseAResponse.step.js
  test/e2e/pages/respondent/contactDetails.step.js
  test/e2e/pages/respondent/done.step.js
  test/e2e/pages/respondent/hasSolicitor.step.js
  test/e2e/pages/respondent/jurisdiction.step.js
  test/e2e/pages/respondent/legalProceedings.step.js
  test/e2e/pages/respondent/respond.step.js
  test/e2e/pages/respondent/reviewApplication.step.js
Labels: ns:div-rfe-pr-388

#393 PROD FIX: parse feature as bool so it copes with strings
  app.js
Labels: ns:div-rfe-pr-393

#391 Use hmcts/cnp modules
  infrastructure/main.tf
Labels: ns:div-rfe-pr-391

#385 Add aria-labels for what this means expandable sections
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/respondent/jurisdiction/Jurisdiction.html
  steps/respondent/review-application/ReviewApplication.html
Labels: ns:div-rfe-pr-385

#397 Accessibility statement
  config/default.yml
  steps/accessibility-statement/AccessibilityStatement.content.json
  steps/accessibility-statement/AccessibilityStatement.html
  steps/accessibility-statement/AccessibilityStatement.step.js
  test/unit/steps/accessibilityStatement.test.js
  views/check_your_answers.njk
  views/page.njk
  views/question.njk
Labels: ns:div-rfe-pr-397

#356 DIV-5049 - Add address input for respondent solicitor on RFE
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  charts/div-rfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  infrastructure/main.tf
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  middleware/compactPostValuesMiddleware.js
  middleware/postcodeLookupMiddleware.js
  mocks/services/postcode-lookup/addresses/postcode/GET--postcode=bad&key=null.mock
  mocks/services/postcode-lookup/addresses/postcode/GET.mock
  mocks/services/postcode-lookup/addresses/postcode/mock-postcode-list.json
  package.json
  services/postcodeLookup.js
  services/setupSecrets.js
  steps/respondent/solicitor-address/SolicitorAddress.content.json
  steps/respondent/solicitor-address/SolicitorAddress.html
  steps/respondent/solicitor-address/SolicitorAddress.step.js
  steps/respondent/solicitor-address/templates/address.html
  steps/respondent/solicitor-address/templates/confirmAddress.html
  steps/respondent/solicitor-address/templates/editAddress.html
  steps/respondent/solicitor-address/templates/manualAddress.html
  steps/respondent/solicitor-address/templates/postcodeSearch.html
  steps/respondent/solicitor-address/templates/selectAddress.html
  steps/respondent/solicitor-details/SolicitorDetails.step.js
  test/e2e/pages/respondent/solicitorAddress.js
  test/e2e/paths/respondent/solicitorAddress.js
  test/e2e/paths/respondent/solicitorNominatePath.js
  test/unit/middleware/compactPostValuesMiddleware.test.js
  test/unit/middleware/postcodeLookupMiddleware.test.js
  test/unit/services/postcodeLookup.test.js
  test/unit/services/setupSecrets.test.js
  test/unit/steps/respondent/solicitorAddress.test.js
  test/unit/steps/respondent/solicitorDetails.test.js
  test/unit/views/filters/lineBreakToComma.test.js
  views/filters/lineBreakToComma.js
  yarn.lock
Labels: ns:div-rfe-pr-356

#395 use correct node version on aat and prod
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-395

#396 DIV-5552 Update to OPP 5.3.0
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-396

#401 Remove escaping html entities for Address lookup because the middlewa…
  services/postcodeLookup.js
  test/unit/services/postcodeLookup.test.js
Labels: ns:div-rfe-pr-401
