Repository hmcts/div-respondent-frontend, pull requests merged in 2019-06, with the labels that each got.

#313 DIV-3999: Consolidate naming of responses in health check
  middleware/healthcheck.js
Labels: ns:div-rfe-pr-313

#311 add coe file to respondent and co-respondent
  app.js
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case-two-dates.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingSubmittedAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingWaitingAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespTooLateToRespond.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/respond/Respond.content.json
  test/e2e/pages/co-respondent/crRespond.step.js
  test/e2e/pages/respondent/respond.step.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/corespondent/crRespond.test.js
  test/unit/steps/respondent/progressBar.test.js
  test/unit/steps/respondent/respond.test.js
Labels: ns:div-rfe-pr-311

#310 DIV-4622 screen reader reads case reference ID as seperate characters
  assets/scss/main.scss
  steps/co-respondent/cr-done/CrDone.html
  steps/respondent/done/Done.html
  test/unit/views/filters/a11y.test.js
  test/w3cjs/index.js
  views/filters/a11y.js
  views/page.njk
Labels: ns:div-rfe-pr-310

#316 Awaiting pronouncement with hearing date - respondent
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesDecreeNisiPronouncement.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-decree-nisi-pronouncement.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  sonar-project.properties
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-316

#322 Awaiting pronouncement with hearing date - co respondent
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespAwaitingPronouncementHearingDataFuture.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespAwaitingPronouncementHearingDataFuture.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  services/documentHandler.js
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.html
  steps/co-respondent/cr-progress-bar/CrProgressBar.step.js
  steps/co-respondent/cr-respond/CrRespond.content.json
  test/e2e/pages/co-respondent/crProgressBar.js
  test/e2e/pages/common/idam.step.js
  test/e2e/paths/co-respondent/progressBar.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/corespondent/crRespond.test.js
Labels: ns:div-rfe-pr-322

#327 Update demo with master - demoupdate
  assets/scss/main.scss
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespAwaitingPronouncementHearingDataFuture.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesDecreeNisiPronouncement.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespAwaitingPronouncementHearingDataFuture.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-decree-nisi-pronouncement.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  services/documentHandler.js
  sonar-project.properties
  steps/co-respondent/cr-done/CrDone.html
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.html
  steps/co-respondent/cr-progress-bar/CrProgressBar.step.js
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/respondent/done/Done.html
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  test/e2e/pages/co-respondent/crProgressBar.js
  test/e2e/pages/common/idam.step.js
  test/e2e/paths/co-respondent/progressBar.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/corespondent/crRespond.test.js
  test/unit/steps/respondent/progressBar.test.js
  test/unit/views/filters/a11y.test.js
  test/w3cjs/index.js
  views/filters/a11y.js
  views/page.njk
Labels: ns:div-rfe-pr-327

#320 DIV-4629 Adding two steps for respondent solicitor submission
  .eslintrc.json
  Jenkinsfile_CNP
  charts/div-rfe/values.aat.template.yaml
  charts/div-rfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  steps/respondent/progress-bar/ProgressBar.step.js
  steps/respondent/review-application/ReviewApplication.step.js
  steps/respondent/solicitor-details/SolicitorDetails.content.json
  steps/respondent/solicitor-details/SolicitorDetails.html
  steps/respondent/solicitor-details/SolicitorDetails.step.js
  steps/respondent/solicitor-representation/SolicitorRepresentation.content.json
  steps/respondent/solicitor-representation/SolicitorRepresentation.html
  steps/respondent/solicitor-representation/SolicitorRepresentation.step.js
  test/.eslintrc.json
  test/e2e/pages/respondent/hasSolicitor.step.js
  test/e2e/pages/respondent/solicitorDetails.js
  test/e2e/paths/respondent/happyPath.js
  test/e2e/paths/respondent/solicitorNominatePath.js
  test/unit/steps/respondent/reviewApplication.test.js
  test/unit/steps/respondent/solicitorDetails.test.js
  test/unit/steps/respondent/solicitorRepresentation.test.js
Labels: ns:div-rfe-pr-320

#324 DIV-3264: Update readme
  README.md
Labels: ns:div-rfe-pr-324

#325 decree nisi granted
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer awaitingDecreeAbsolute.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-awaitingDecreeAbsolute.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/respondent/progressBar.js
  test/e2e/paths/respondent/progressBar.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-325

#331 DIV-5153 - Bold text on DN & AOS confirmation page
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.html
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-331
