Repository hmcts/div-respondent-frontend, pull requests merged in 2019-02, with the labels that each got.

#209 DIV-4160: Removed redundant word
  steps/financial-situation/FinancialSituation.content.json
Labels: ns:div-rfe-pr-209

#192 use progress list from look-and-feel
  app.js
  assets/scss/main.scss
  package.json
  steps/done/Done.html
  steps/respond/Respond.html
Labels: ns:div-rfe-pr-192

#208 Progress step add graphics
  assets/scss/main.scss
  steps/progress-bar/ProgressBar.content.json
  steps/progress-bar/ProgressBar.html
  steps/progress-bar/ProgressBar.step.js
  steps/progress-bar/sections/FourCircleFilledIn.html
  steps/progress-bar/sections/OneCircleFilledIn.html
  steps/progress-bar/sections/OneCircleFilledInBold.html
  steps/progress-bar/sections/ThreeCircleFilledInBold.html
  steps/progress-bar/sections/TwoCircleFilledIn.html
  steps/progress-bar/sections/TwoCircleFilledInBold.html
  test/unit/steps/progressBar.test.js
Labels: ns:div-rfe-pr-208

#210 DIV-4159 Ensure session is clean if user must re-answer confirm defence question
  steps/confirm-defence/ConfirmDefence.step.js
Labels: ns:div-rfe-pr-210

#213 DIV-4159 5yrs defended bug (fixes 2yr separation issue)
  steps/confirm-defence/ConfirmDefence.step.js
Labels: ns:div-rfe-pr-213

#217 DIV-4217 Added testing for Confirm Defence re-direct bug
  test/unit/steps/confirmDefence.test.js
Labels: ns:div-rfe-pr-217

#223 DIV 3987 confirm defend, DIV-3988 Agree to pay costs for correspondent
  config/default.yml
  steps/corespondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.content.json
  steps/corespondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.html
  steps/corespondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.step.js
  steps/corespondent/cr-choose-a-response/CrChooseAResponse.step.js
  steps/corespondent/cr-confirm-defence/CrConfirmDefence.content.json
  steps/corespondent/cr-confirm-defence/CrConfirmDefence.html
  steps/corespondent/cr-confirm-defence/CrConfirmDefence.step.js
  test/e2e/pages/corespondent/crAgreeToPayCosts.step.js
  test/e2e/pages/corespondent/crConfirmDefence.step.js
  test/e2e/paths/corespondent/adulteryJourney.js
  test/unit/steps/corespondent/crAgreeToPayCosts.test.js
  test/unit/steps/corespondent/crChooseAResponse.test.js
  test/unit/steps/corespondent/crConfirmDefence.test.js
Labels: ns:div-rfe-pr-223

#222 Add missing text reference css class
  assets/scss/main.scss
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-222

#232 Sonar Duplicate checks excluded
  sonar-project.properties
Labels: ns:div-rfe-pr-232

#211 Activate ACR build, image multistaging and hmcts runtime user
  .dockerignore
  .gitignore
  Dockerfile
  acb.tpl.yaml
  kubernetes/deployment.template.yaml
Labels: docker-optimisation, ns:div-rfe-pr-211

#231 Change deprecated RespDefendsDivorce to te RespWillDefendDivorce field
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/awaiting-answer.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/defended.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/no-aos.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  steps/respondent/consent-decree/ConsentDecree.step.js
  steps/respondent/progress-bar/ProgressBar.step.js
  test/unit/services/googleAnalytics.test.js
  test/unit/steps/respondent/consentDecree.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-231

#228 DIV-4052: Remove non numerical characters from case ref number when linking case
  services/caseOrchestration.js
  steps/capture-case-and-pin/CaptureCaseAndPin.content.json
  steps/capture-case-and-pin/CaptureCaseAndPin.step.js
  test/e2e/paths/respondent/captureCaseAndPin.js
  test/unit/services/caseOrchestration.test.js
  test/unit/steps/respondent/captureCaseAndPin.test.js
  yarn.lock
Labels: ns:div-rfe-pr-228

#236 CoRespondentEmailAddress is fetched from coRespondentAnswers.contactI…
  middleware/redirectMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  test/unit/middleware/redirectMiddleware.test.js
Labels: ns:div-rfe-pr-236

#214 Text change made to reasons of divorce
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesDesertion.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-214

#234 Contact details page for corespondent
  config/default.yml
  middleware/petitionMiddleware.js
  middleware/redirectMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  steps/co-respondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.step.js
  steps/co-respondent/cr-confirm-defence/CrConfirmDefence.step.js
  steps/co-respondent/cr-contact-details/CrContactDetails.content.json
  steps/co-respondent/cr-contact-details/CrContactDetails.html
  steps/co-respondent/cr-contact-details/CrContactDetails.step.js
  test/e2e/pages/co-respondent/crContactDetails.step.js
  test/e2e/paths/co-respondent/adulteryJourney.js
  test/unit/middleware/petitionMiddleware.test.js
  test/unit/middleware/redirectMiddleware.test.js
  test/unit/steps/corespondent/crAgreeToPayCosts.test.js
  test/unit/steps/corespondent/crConfirmDefence.test.js
  test/unit/steps/corespondent/crContactDetails.test.js
Labels: ns:div-rfe-pr-234

#233 add third response option if desertion
  steps/respondent/choose-a-response/ChooseAResponse.html
  steps/respondent/choose-a-response/ChooseAResponse.step.js
  test/unit/steps/respondent/chooseAResponse.test.js
Labels: ns:div-rfe-pr-233

#225 [PREVIEW] Div 3990 cr cya
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  kubernetes/config.aat.yaml
  services/caseOrchestration.js
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.content.json
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.html
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.step.js
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-done/CrDone.html
  steps/co-respondent/cr-done/CrDone.step.js
  test/e2e/pages/co-respondent/crCheckYourAnswers.step.js
  test/e2e/paths/co-respondent/adulteryJourney.js
  test/unit/services/caseOrchestration.test.js
  test/unit/steps/corespondent/crCheckYouAnswers.test.js
Labels: ns:div-rfe-pr-225
