Repository hmcts/div-respondent-frontend, pull requests merged in 2019-01, with the labels that each got.

#180 Enable CSRF and fix local mocks for local testing
  app.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  steps/check-your-answers/CheckYourAnswers.html
Labels: ns:div-rfe-pr-180

#181 Enforce minimum version of OPP for santisation
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-181

#182 DIV-3830: Changed simulate email address with valid gmail for int tests
  test/e2e/helpers/idamHelper.js
  test/unit/steps/done.test.js
Labels: ns:div-rfe-pr-182

#176 update choose a response answers
  steps/choose-a-response/ChooseAResponse.content.json
  steps/choose-a-response/ChooseAResponse.step.js
  test/unit/steps/chooseAResponse.test.js
Labels: ns:div-rfe-pr-176

#184 Add missing guidance link in right hand side menu
  steps/done/Done.content.json
  steps/done/Done.html
  steps/progress-bar/ProgressBar.content.json
  steps/progress-bar/ProgressBar.html
  steps/respond/Respond.content.json
  steps/respond/Respond.html
  test/unit/steps/done.test.js
  test/unit/steps/progressBar.test.js
  test/unit/steps/respond.test.js
  views/includes/sideMenuGuidanceLinks.html
Labels: ns:div-rfe-pr-184

#185 DIV-3888 error page update
  app.js
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer throwError.mock
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  test/e2e/pages/error.js
  test/e2e/pages/idam.step.js
  test/e2e/paths/errors.js
  views/errors/content.html
  views/errors/error-content.json
  views/errors/footer.html
  views/errors/header.html
  views/errors/not-found-error.html
  views/errors/server-error.html
Labels: ns:div-rfe-pr-185

#178 DIV-3849 - Enter more specific regex for dealing with case numbers
  steps/capture-case-and-pin/CaptureCaseAndPin.content.json
  steps/capture-case-and-pin/CaptureCaseAndPin.step.js
  test/e2e/paths/captureCaseAndPin.js
  test/unit/steps/captureCaseAndPin.test.js
Labels: ns:div-rfe-pr-178

#188 [PREVIEW] DIV-3853 Apply infra for app insights config
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-rfe-pr-188

#191 Add google analytics tracking ID for prod
  infrastructure/prod.tfvars
Labels: ns:div-rfe-pr-191

#194 Fix healthcheck tests
  test/unit/middleware/healthcheck.test.js
Labels: ns:div-rfe-pr-194

#196 Revert dot to hyphen references in OPP
  package.json
  test/unit/steps/agreeToPayCosts.test.js
  test/unit/steps/consentDecree.test.js
  test/unit/steps/contactDetails.test.js
  test/unit/steps/defendFinancialHardship.test.js
  test/unit/steps/jurisdiction.test.js
  test/unit/steps/legalProceedings.test.js
  yarn.lock
Labels: ns:div-rfe-pr-196

#197 Remove unused dependancy
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-197

#202 add idam id and ccd id to logs
  app.js
  middleware/feesAndPaymentsMiddleware.js
  middleware/healthcheck.js
  middleware/petitionMiddleware.js
  server.js
  services/caseOrchestration.js
  services/getCcdData.js
  services/logger.js
  services/redis.js
  steps/progress-bar/ProgressBar.step.js
  test/e2e/helpers/caseHelper.js
  test/unit/services/logger.test.js
Labels: ns:div-rfe-pr-202

#162 [PREVIEW] AOS - 5 year separation - revised 'review petition' page
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yes5yrSeparationTwoDates.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case-two-dates.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/review-application/ReviewApplication.content.json
  steps/review-application/ReviewApplication.html
  test/unit/steps/reviewApplication.test.js
Labels: ns:div-rfe-pr-162

#199 Changed divorce to divorcecase court email address
  common/content.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  steps/end/End.content.json
  test/unit/helpers/courtInformation.js
  test/unit/resources/courtsList.json
  views/errors/error-content.json
Labels: ns:div-rfe-pr-199

#167 DIV-3734 Updated content with FinancialConsideration
  steps/done/Done.content.json
  steps/done/Done.html
  steps/financial-situation/FinancialSituation.content.json
  test/unit/steps/done.test.js
Labels: ns:div-rfe-pr-167
