Repository hmcts/div-respondent-frontend, pull requests merged in 2019-03, with the labels that each got.

#237 Div 4257 submit co respondent
  mocks/services/case-orchestration/submit-co-respondent-aos/POST.mock
  steps/co-respondent/cr-admit-adultery/CrAdmitAdultery.step.js
  steps/co-respondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.step.js
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.html
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.step.js
  steps/co-respondent/cr-choose-a-response/CrChooseAResponse.step.js
  steps/co-respondent/cr-contact-details/CrContactDetails.html
  steps/co-respondent/cr-contact-details/CrContactDetails.step.js
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/co-respondent/cr-review-application/CrReviewApplication.step.js
  test/unit/steps/corespondent/crAdmitAdultery.test.js
  test/unit/steps/corespondent/crAgreeToPayCosts.test.js
  test/unit/steps/corespondent/crCheckYouAnswers.test.js
  test/unit/steps/corespondent/crChooseAResponse.test.js
  test/unit/steps/corespondent/crContactDetails.test.js
  test/unit/steps/corespondent/crReviewApplication.test.js
  yarn.lock
Labels: ns:div-rfe-pr-237

#242 DIV-4362: Force versions of underscore.string & braces to remove all vulns
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-242

#240 DIV-3991: Created CRDone page & dynamic content
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-done/CrDone.html
  steps/co-respondent/cr-done/CrDone.step.js
  test/unit/steps/corespondent/crContactDetails.test.js
  test/unit/steps/corespondent/crDone.test.js
  yarn.lock
Labels: ns:div-rfe-pr-240

#244 Content added specific to co-respondent
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/corespondent/crReviewApplication.test.js
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-244

#241 Desertion agreement details added in mini-petition
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-241

#251 Linking may take time - Info Content added
  steps/capture-case-and-pin/CaptureCaseAndPin.content.json
  steps/capture-case-and-pin/CaptureCaseAndPin.html
Labels: ns:div-rfe-pr-251

#250 Show claim costs page only when petitioner claims costs from corespon…
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  package.json
  steps/co-respondent/cr-choose-a-response/CrChooseAResponse.step.js
  steps/co-respondent/cr-confirm-defence/CrConfirmDefence.step.js
  test/unit/steps/corespondent/crChooseAResponse.test.js
  test/unit/steps/corespondent/crConfirmDefence.test.js
  yarn.lock
Labels: ns:div-rfe-pr-250

#239 Update ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.content.json
Labels: ns:div-rfe-pr-239

#248 Help content updated - Reason for divorce section
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
Labels: ns:div-rfe-pr-248

#259 update google analytics setting for production
  infrastructure/prod.tfvars
  middleware/helmet.js
  test/unit/middleware/helmet.test.js
  test/unit/services/googleAnalytics.test.js
  views/includes/head.html
Labels: ns:div-rfe-pr-259

#260 Added bold style to email
  steps/co-respondent/cr-contact-details/CrContactDetails.html
Labels: ns:div-rfe-pr-260

#245 DIV-4371 - Show additional adultery information got from another person
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-245

#255 Updating all content on this screen
  steps/co-respondent/cr-choose-a-response/CrChooseAResponse.content.json
Labels: ns:div-rfe-pr-255

#246 DIV-4372 second hand info in review application for co-respondent
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  test/unit/steps/corespondent/crReviewApplication.test.js
Labels: ns:div-rfe-pr-246

#256 new content for corespondent done page
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-done/CrDone.html
  steps/co-respondent/cr-done/CrDone.step.js
  test/unit/steps/corespondent/crDone.test.js
Labels: ns:div-rfe-pr-256

#227 Respondent: Amend 'defend' workflow for 5-Year Separation.
  package.json
  steps/respondent/choose-a-response/ChooseAResponse.content.json
  steps/respondent/choose-a-response/ChooseAResponse.step.js
  steps/respondent/confirm-defence/ConfirmDefence.step.js
  steps/respondent/defend-financial-hardship/DefendFinancialHardship.step.js
  test/unit/steps/respondent/chooseAResponse.test.js
  test/unit/steps/respondent/confirmDefence.test.js
  test/unit/steps/respondent/defendFinancialHardship.test.js
  yarn.lock
Labels: ns:div-rfe-pr-227

#262 DIV-4510: Fixed content on CR review application page
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
Labels: ns:div-rfe-pr-262

#257 SAAT and SIDAM Setup
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  config/example-local-aat.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  middleware/healthcheck.js
  package.json
  test/e2e/codecept.conf.js
  test/e2e/codecept.smoke.conf.js
  test/e2e/helpers/idamHelper.js
  yarn.lock
Labels: ns:div-rfe-pr-257

#265 DIV-4510: Fixed content on respondent review application page
  package.json
  steps/respondent/review-application/ReviewApplication.content.json
  yarn.lock
Labels: ns:div-rfe-pr-265
