Repository hmcts/div-respondent-frontend, pull requests merged in 2019-08, with the labels that each got.

#358 Fixed Unit and E2E test issues
  middleware/helmet.js
  mocks/steps/idamLogin/IdamLogin.content.json
  package.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  test/e2e/pages/co-respondent/crProgressBar.js
  test/e2e/pages/co-respondent/crRespond.step.js
  test/e2e/pages/common/error.js
  test/e2e/pages/respondent/progressBar.js
  test/e2e/paths/co-respondent/progressBar.js
  test/unit/middleware/helmet.test.js
  test/unit/mocha-init.js
  test/unit/mocha.opts
  test/unit/services/idam.test.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/respondent/reviewApplication.test.js
  test/unit/views/filters/date.test.js
  yarn.lock
Labels: ns:div-rfe-pr-358

#360 Ensure Jenkins AAT env is feature flagged off
  Jenkinsfile_CNP
  infrastructure/preview.tfvars
Labels: ns:div-rfe-pr-360

#361 DIV-4001 - Upgrade to the latest nodejs version
  .nvmrc
  Dockerfile
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-361

#359 update look-and-feel version to use new check your answers page layout
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-359

#363 add more wait to crOss browser tests
  test/e2e/paths/respondent/happyPath.js
  yarn.lock
Labels: ns:div-rfe-pr-363

#364 Fix cross browser tests
  test/crossbrowser/supportedBrowsers.js
  test/e2e/pages/common/captureCaseIdAndPin.step.js
  test/e2e/pages/respondent/agreeToPayCosts.step.js
  test/e2e/pages/respondent/checkYourAnswers.step.js
  test/e2e/pages/respondent/chooseAResponse.step.js
  test/e2e/pages/respondent/contactDetails.step.js
  test/e2e/pages/respondent/done.step.js
  test/e2e/pages/respondent/jurisdiction.step.js
  test/e2e/pages/respondent/legalProceedings.step.js
  test/e2e/pages/respondent/progressBar.js
  test/e2e/pages/respondent/respond.step.js
  test/e2e/pages/respondent/reviewApplication.step.js
  test/e2e/paths/respondent/happyPath.js
Labels: ns:div-rfe-pr-364

#367 Fix heading structure
  package.json
  steps/respondent/check-your-answers/CheckYourAnswers.html
  steps/respondent/review-application/ReviewApplication.html
  views/includes/sideMenu.html
  views/includes/sideMenuCoRespondent.html
  yarn.lock
Labels: ns:div-rfe-pr-367

#368 DIV-5634 - Update vault definitions for DN, RFE and PFE
  Jenkinsfile_CNP
  package.json
Labels: ns:div-rfe-pr-368

#369 retry request to validate html
  test/w3cjs/index.js
Labels: ns:div-rfe-pr-369

#373 Fix vault on nightly
  Jenkinsfile_nightly
Labels: ns:div-rfe-pr-373

#379 DIV-5694 Fix IDAM chart tags syntax
  charts/div-rfe/values.preview.template.yaml
Labels: ns:div-rfe-pr-379

#381 Revert IDAM tag
  charts/div-rfe/values.preview.template.yaml
Labels: ns:div-rfe-pr-381
