Repository hmcts/div-respondent-frontend, pull requests merged in 2019-04, with the labels that each got.

#249 DIV-4386: Adding phrase to privacy page
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/privacy-policy/PrivacyPolicy.html
Labels: ns:div-rfe-pr-249

#275 Disable prod deployments
  Jenkinsfile_CNP
Labels: ns:div-rfe-pr-275

#247 update content for mini petition help section
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
Labels: ns:div-rfe-pr-247

#270 No javascript phase one
  app.js
  views/page.njk
  views/question.njk
Labels: ns:div-rfe-pr-270

#267 Mini petition - Amend case reissue date changes
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/corespondent/crReviewApplication.test.js
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-267

#261 Div 4479 mini petition
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/corespondent/crReviewApplication.test.js
  test/unit/steps/respondent/reviewApplication.test.js
Labels: ns:div-rfe-pr-261

#264 DIV-4485: changing landing page title for amended cases
  Jenkinsfile_CNP
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer co-respondent-amended-case.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesAdulteryAmendedCase.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/co-respondent/cr-respond/CrRespond.html
  steps/respondent/respond/Respond.content.json
  steps/respondent/respond/Respond.html
  test/unit/steps/corespondent/crDone.test.js
  test/unit/steps/corespondent/crRespond.test.js
  test/unit/steps/respondent/respond.test.js
Labels: ns:div-rfe-pr-264

#279 DIV-4665 - fixed incorrect content for co-respondent
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  yarn.lock
Labels: ns:div-rfe-pr-279

#276 DIV-4572 Update content on "How do you want to respond?"
  steps/respondent/choose-a-response/ChooseAResponse.content.json
  test/unit/steps/respondent/chooseAResponse.test.js
Labels: ns:div-rfe-pr-276

#271 When the user change response it should always go back to previous sc…
  steps/co-respondent/cr-confirm-defence/CrConfirmDefence.step.js
Labels: ns:div-rfe-pr-271

#280 DIV-4665 - renamed petitioner to applicant in co-respondent review page
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  config/ci.yml
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  test/e2e/helpers/idamHelper.js
Labels: ns:div-rfe-pr-280

#281 DIV-4665 - set NODE_ENV in master pipeline for AAT testes
  Jenkinsfile_CNP
  test/e2e/helpers/idamHelper.js
Labels: ns:div-rfe-pr-281

#282 DIV-4663: Lowering severity in log message. This is actually the normal flow.
  middleware/petitionMiddleware.js
Labels: ns:div-rfe-pr-282

#268 DIV-3773 Added helm chart config
  Jenkinsfile_CNP
  app.js
  charts/div-rfe/Chart.yaml
  charts/div-rfe/requirements.yaml
  charts/div-rfe/values.aat.template.yaml
  charts/div-rfe/values.preview.template.yaml
  charts/div-rfe/values.yaml
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  package.json
  server.js
  services/idam.js
  services/setupSecrets.js
  test/e2e/helpers/idamHelper.js
  test/unit/services/setupSecrets.test.js
  yarn.lock
Labels: ns:div-rfe-pr-268

#266 DIV-4527 Add/amend logging for Respondent journey
  middleware/petitionMiddleware.js
  middleware/redirectMiddleware.js
Labels: ns:div-rfe-pr-266

#286 Redirect to capture pin page when case state is aos awaiting
  middleware/petitionMiddleware.js
  test/unit/middleware/petitionMiddleware.test.js
Labels: ns:div-rfe-pr-286

#285 DIV-4683 Respondent download docs
  app.js
  assets/scss/main.scss
  charts/div-rfe/values.aat.template.yaml
  charts/div-rfe/values.preview.template.yaml
  config/custom-environment-variables.yml
  config/default.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  middleware/healthcheck.js
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/awaiting-answer.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/defended.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/no-aos.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case-two-dates.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingSubmittedAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingWaitingAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespTooLateToRespond.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
  mocks/services/evidence-managment/documents/__/GET.mock
  mocks/services/idam.js
  package.json
  services/documentHandler.js
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  steps/respondent/respond/Respond.content.json
  steps/respondent/respond/Respond.html
  steps/respondent/respond/Respond.step.js
  test/unit/middleware/healthcheck.test.js
  test/unit/services/documentHandler.test.js
  test/unit/steps/respondent/respond.test.js
  test/unit/views/filters/hypenate.test.js
  test/unit/views/filters/upper.test.js
  views/filters/upper.js
  yarn.lock
Labels: ns:div-rfe-pr-285

#290 Add happy path to saucelabs crossbrowser
  .eslintignore
  .gitignore
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yml
  config/default.yml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/e2e/helpers/sauceLabsReportingHelper.js
  test/e2e/paths/respondent/happyPath.js
  test/e2e/saucelabs.conf.js
  yarn.lock
Labels: ns:div-rfe-pr-290

#293 Change AAT additional hostname
  infrastructure/aat.tfvars
Labels: ns:div-rfe-pr-293

#215 set up divorce respondent app security scan and performance
  security.sh
Labels: ns:div-rfe-pr-215
