Repository hmcts/div-respondent-frontend, pull requests merged in 2019-07, with the labels that each got.

#326 DIV-5103 - Update email address for divorce cases
  common/content.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingSubmittedAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingWaitingAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespTooLateToRespond.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  steps/end/End.content.json
  test/unit/helpers/courtInformation.js
  test/unit/resources/courtsList.json
  views/errors/error-content.json
Labels: ns:div-rfe-pr-326

#332 DIV-5167 - Add state "DNPronounced"
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer dnPronounced.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-dnPronounced.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/respondent/progressBar.js
  test/e2e/paths/respondent/progressBar.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-332

#329 DIV-4897 Ensure data is correct for solicitor submission
  steps/respondent/check-your-answers/CheckYourAnswers.content.json
  steps/respondent/check-your-answers/CheckYourAnswers.html
  steps/respondent/check-your-answers/CheckYourAnswers.step.js
  steps/respondent/solicitor-representation/SolicitorRepresentation.step.js
  test/e2e/pages/respondent/checkYourAnswers.step.js
  test/unit/steps/respondent/checkYourAnswers.test.js
  test/unit/steps/respondent/solicitorRepresentation.test.js
Labels: ns:div-rfe-pr-329

#341 update npm dependancies
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-341

#342 DIV-4698: use warnWithReq in ProgressBar.step.js
  steps/respondent/progress-bar/ProgressBar.step.js
Labels: ns:div-rfe-pr-342

#340 DIV-5251: Redirect Respondent to DA if divorce is granted
  charts/div-rfe/values.aat.template.yaml
  charts/div-rfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  middleware/petitionMiddleware.js
  middleware/redirectMiddleware.js
Labels: ns:div-rfe-pr-340

#344 Update to use the public HMCTS docker registry
  Dockerfile
  acb.tpl.yaml
Labels: ns:div-rfe-pr-344

#343 DIV-5316: Fixed Error Message on Production and Fixed Error When ClaimsCostFrom…
  steps/respondent/review-application/ReviewApplication.html
  steps/respondent/review-application/ReviewApplication.step.js
  test/unit/steps/respondent/reviewApplication.test.js
  views/errors/content.html
  views/errors/error.html
Labels: ns:div-rfe-pr-343

#347 Add gov-uk-body class when not a bullet list for jurisdictions
  steps/respondent/review-application/ReviewApplication.html
Labels: ns:div-rfe-pr-347

#353 Added unit test to confirm redirection to DA logic is called
  test/unit/middleware/petitionMiddleware.test.js
Labels: ns:div-rfe-pr-353

#350 Div 4900 progress bar page for aos awaiting sol
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer aosAwaitingSol.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-aosAwaitingSol.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/respondent/done/Done.content.json
  steps/respondent/done/Done.html
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/progress-bar/ProgressBar.html
  steps/respondent/progress-bar/ProgressBar.step.js
  steps/respondent/progress-bar/sections/SolicitorOneCircleFilledInBold.html
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/respondent/progressBar.js
  test/e2e/paths/respondent/progressBar.js
  test/unit/steps/respondent/done.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:div-rfe-pr-350

#337 DIV-4892 - Co-Respondent landing page with Cost Order
  config/default.yml
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespDNPronouncedWithCosts.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespDNPronouncedWithoutCosts.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithCosts.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithoutCosts.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.html
  steps/co-respondent/cr-progress-bar/CrProgressBar.step.js
  steps/respondent/progress-bar/ProgressBar.html
  test/e2e/pages/co-respondent/crProgressBar.js
  test/e2e/pages/common/idam.step.js
  test/e2e/paths/co-respondent/progressBar.js
  test/unit/steps/corespondent/crProgressBar.test.js
Labels: ns:div-rfe-pr-337

#357 change domain
  test/e2e/helpers/idamHelper.js
Labels: ns:div-rfe-pr-357
