Repository hmcts/div-respondent-frontend, pull requests merged in 2019-10, with the labels that each got.

#399 DIV-5040 - turn on feature flag for respondent solicitor
  charts/div-rfe/values.aat.template.yaml
  charts/div-rfe/values.preview.template.yaml
  config/default.yml
  infrastructure/aat.tfvars
  infrastructure/variables.tf
Labels: ns:div-rfe-pr-399

#400 Allow co-respondent to respond when case in AosAwaitingSol
  config/default.yml
Labels: ns:div-rfe-pr-400

#375 DIV-4587 - Accessibility [AA]: Ambiguous links
  package.json
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/cookies-policy/CookiesPolicy.content.json
  steps/end/End.content.json
  steps/privacy-policy/PrivacyPolicy.content.json
  steps/respondent/done/Done.content.json
  steps/respondent/jurisdiction/Jurisdiction.html
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/respond/Respond.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/corespondent/crDone.test.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/corespondent/crRespond.test.js
  yarn.lock
Labels: ns:div-rfe-pr-375

#403 Webchats - add live environment variables
  infrastructure/prod.tfvars
Labels: ns:div-rfe-pr-403

#405 DIV-5914 - Use the correct opening hours for the website messages
  common/content.json
Labels: ns:div-rfe-pr-405

#410 Fixup chart and upgrade appinsights
  .editorconfig
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.preview.template.yaml
  charts/div-rfe/values.yaml
  package.json
  services/app-insights.js
  services/setupSecrets.js
  test/unit/services/app-insights.test.js
  yarn.lock
Labels: ns:div-rfe-pr-410

#411 Add missed variable for AKS
  services/setupSecrets.js
Labels: ns:div-rfe-pr-411

#406 DIV-5756 - Enable webchat on live environment
  charts/div-rfe/values.preview.template.yaml
  config/default.yml
  infrastructure/variables.tf
Labels: ns:div-rfe-pr-406

#412 Fix typo for AKS
  services/setupSecrets.js
Labels: ns:div-rfe-pr-412

#407 DIV-5915 Fix AosOverdue cases - allow respondent to proceed
  middleware/petitionMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesAosOverdue.mock
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/aos-overdue.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  test/unit/middleware/petitionMiddleware.test.js
Labels: ns:div-rfe-pr-407

#413 Change base image to alpine
  Dockerfile
  docker-compose.yaml
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-413

#414 Removed nsp dependency as it's been deprecated and our pipeline no longer requires it
  package.json
  yarn.lock
Labels: ns:div-rfe-pr-414

#416 DIV-6508: Swapped to new smart survey urls
  app.js
  infrastructure/variables.tf
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/respondent/done/Done.content.json
  steps/respondent/progress-bar/ProgressBar.content.json
  yarn.lock
Labels: ns:div-rfe-pr-416
