Repository hmcts/div-respondent-frontend, pull requests merged in 2020-07, with the labels that each got.

#457 RPET-299-app-insights-config
  server.js
  services/setupSecrets.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-457

#459 WLA-591: Welsh copy amends
  steps/respondent/choose-a-response/ChooseAResponse.content.json
  steps/respondent/defend-financial-hardship/DefendFinancialHardship.content.json
  steps/respondent/legal-proceedings/LegalProceedings.content.json
  steps/respondent/review-application/ReviewApplication.content.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-459

#462 remove yarn audit as its now run elsewhere
  Jenkinsfile_CNP
Labels: ns:divorce, prd:div, rel:div-rfe-pr-462

#456 WLA-589: Enable Language Preference e2e
  config/default.yml
  package.json
  steps/respondent/language-preference/LanguagePreference.content.json
  steps/respondent/language-preference/LanguagePreference.html
  steps/respondent/language-preference/LanguagePreference.step.js
  steps/respondent/review-application/ReviewApplication.step.js
  test/e2e/pages/respondent/languagePreference.step.js
  test/e2e/paths/respondent/5yrSeparationJourney.js
  test/e2e/paths/respondent/happyPath.js
  test/unit/steps/respondent/languagePreference.test.js
  test/unit/steps/respondent/reviewApplication.test.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-456

#460 PCQ-390: PCQ Integration
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.preview.template.yaml
  charts/div-rfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  config/testing.yaml
  package.json
  services/caseOrchestration.js
  services/setupSecrets.js
  steps/co-respondent/cr-contact-details/CrContactDetails.step.js
  steps/equality/Equality.html
  steps/equality/Equality.step.js
  steps/equality/createToken.js
  steps/respondent/contact-details/ContactDetails.step.js
  test/a11y/index.js
  test/e2e/pages/common/equality.js
  test/e2e/paths/respondent/happyPath.js
  test/unit/steps/corespondent/crContactDetails.test.js
  test/unit/steps/equality/equality.test.js
  test/unit/steps/respondent/contactDetails.test.js
  test/w3cjs/index.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-460

#467 bump dependencies to remove CVE's
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-467

#468 change dependency versions
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-468
