Repository hmcts/div-respondent-frontend, pull requests merged in 2020-01, with the labels that each got.

#425 Delete ASE
  Jenkinsfile_CNP
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-rfe-pr-425

#426 update aat url for nightly pipeline
  Jenkinsfile_nightly
  audit.json
Labels: ns:divorce, rel:div-rfe-pr-426

#427 Updating ctsc opening hours
  common/content.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/aos-overdue.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/awaiting-answer.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/defended.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/no-aos.json
  mocks/services/case-orchestration/retrieve-aos-case/case-progressed/not-defended.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-2yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case-two-dates.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-5yr-separation-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-aosAwaitingSol.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-awaitingDecreeAbsolute.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-amended-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithCosts.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-dnPronouncedWithoutCosts.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespAwaitingPronouncementHearingDataFuture.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingSubmittedAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespDefendingWaitingAnswer.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespTooLateToRespond.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-decree-nisi-pronouncement.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-desertion-case.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-dnIsRefused.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-dnPronounced.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-petitioner-redirect.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  resources/mock.json
  steps/accessibility-statement/AccessibilityStatement.content.json
  steps/co-respondent/cr-done/CrDone.content.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/end/End.content.json
  steps/respondent/done/Done.content.json
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/respond/Respond.content.json
  test/unit/resources/courtsList.json
  views/errors/error-content.json
Labels: ns:divorce, rel:div-rfe-pr-427

#428 Upgraded node to version 12 from 10
  .nsprc
  .nvmrc
  Dockerfile
  LICENSE
  README.md
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:divorce, rel:div-rfe-pr-428
