Repository hmcts/div-respondent-frontend, pull requests merged in 2020-11, with the labels that each got.

#486 added missing paths to 2+ and 5+ years separation journeys
  test/e2e/paths/respondent/2yrSeparationJourney.js
  test/e2e/paths/respondent/5yrSeparationJourney.js
  test/resources/2PlusYears-divorce-session.json
  test/resources/5PlusYears-divorce-session.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-486

#491 Added test to verify desertion respondent e2e journey
  test/e2e/paths/respondent/desertionJourney.js
  test/resources/desertion-divorce-session.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-491

#492 Added refactored data file, missing paths for correspondent
  test/e2e/helpers/caseHelper.js
  test/e2e/paths/respondent/adulteryJourney.js
  test/resources/corespondent-divorce-session.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-492

#494 Added welsh check for respondent accessibility test
  test/a11y/index.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-494

#493 Ta-56 Behaviour Journey happy path-welsh
  test/e2e/helpers/JSWait.js
  test/e2e/pages/common/captureCaseIdAndPin.step.js
  test/e2e/pages/common/equality.js
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/respondent/agreeToPayCosts.step.js
  test/e2e/pages/respondent/checkYourAnswers.step.js
  test/e2e/pages/respondent/chooseAResponse.step.js
  test/e2e/pages/respondent/contactDetails.step.js
  test/e2e/pages/respondent/done.step.js
  test/e2e/pages/respondent/hasSolicitor.step.js
  test/e2e/pages/respondent/jurisdiction.step.js
  test/e2e/pages/respondent/languagePreference.step.js
  test/e2e/pages/respondent/legalProceedings.step.js
  test/e2e/pages/respondent/respond.step.js
  test/e2e/pages/respondent/reviewApplication.step.js
  test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
  test/e2e/paths/respondent/behaviourNegativeScenarios.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-493

#499 TA-247 Respondent Nightly setup
  Jenkinsfile_nightly
  package.json
  test/e2e/codecept.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-499

#498 Chore: Update crossbrowser config and dependencies
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yaml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/e2e/helpers/JSWait.js
  test/e2e/helpers/caseConfigHelper.js
  test/e2e/helpers/sauceLabsReportingHelper.js
  test/e2e/paths/co-respondent/progressBar.js
  test/e2e/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-498

#472 DIV-6516: Displaying General orders
  config/default.yml
  core/utils/utils.js
  mocks/services/case-orchestration/retrieve-aos-case/mock-awaitingDecreeAbsolute.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefending.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-started-response.json
  steps/co-respondent/cr-progress-bar/CrProgressBar.content.json
  steps/co-respondent/cr-respond/CrRespond.content.json
  steps/respondent/progress-bar/ProgressBar.content.json
  steps/respondent/respond/Respond.content.json
  test/unit/core/utils/utils.test.js
  test/unit/steps/corespondent/crProgressBar.test.js
  test/unit/steps/corespondent/crRespond.test.js
  test/unit/steps/respondent/progressBar.test.js
  test/unit/steps/respondent/respond.test.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-472

#503 TA-247 Respondent Nightly Setup
  Jenkinsfile_nightly
  package.json
  test/e2e/pages/common/equality.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-503

#505 New test branch
  test/e2e/helpers/JSWait.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-505

#501 Feature(TA-292): Add retrying for e2e test user setup, plus other crossbrowser test improvements
  config/default.yml
  test/crossbrowser/supportedBrowsers.js
  test/e2e/codecept.conf.js
  test/e2e/helpers/JSWait.js
  test/e2e/helpers/SauceLabsBrowserHelper.js
  test/e2e/helpers/idamHelper.js
  test/e2e/pages/co-respondent/crAdmitAdultery.step.js
  test/e2e/pages/co-respondent/crAgreeToPayCosts.step.js
  test/e2e/pages/co-respondent/crCheckYourAnswers.step.js
  test/e2e/pages/co-respondent/crChooseAResponse.step.js
  test/e2e/pages/co-respondent/crContactDetails.step.js
  test/e2e/pages/co-respondent/crRespond.step.js
  test/e2e/pages/co-respondent/crReviewApplication.step.js
  test/e2e/pages/common/captureCaseIdAndPin.step.js
  test/e2e/pages/common/equality.js
  test/e2e/pages/common/idam.step.js
  test/e2e/pages/respondent/agreeToPayCosts.step.js
  test/e2e/pages/respondent/checkYourAnswers.step.js
  test/e2e/pages/respondent/chooseAResponse.step.js
  test/e2e/pages/respondent/consent2yrSeparation.js
  test/e2e/pages/respondent/contactDetails.step.js
  test/e2e/pages/respondent/done.step.js
  test/e2e/pages/respondent/financialSituation.js
  test/e2e/pages/respondent/hasSolicitor.step.js
  test/e2e/pages/respondent/jurisdiction.step.js
  test/e2e/pages/respondent/languagePreference.step.js
  test/e2e/pages/respondent/legalProceedings.step.js
  test/e2e/pages/respondent/respond.step.js
  test/e2e/pages/respondent/reviewApplication.step.js
  test/e2e/paths/co-respondent/adulteryJourney.js
  test/e2e/paths/respondent/2yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/5yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
  test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
  test/e2e/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-501

#507 Feature(TA-77): Run crossbrowser tests nightly (2)
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  test/crossbrowser/supportedBrowsers.js
  test/e2e/helpers/JSWait.js
  test/e2e/pages/co-respondent/crChooseAResponse.step.js
  test/e2e/pages/co-respondent/crReviewApplication.step.js
  test/e2e/pages/common/captureCaseIdAndPin.step.js
  test/e2e/pages/common/equality.js
  test/e2e/paths/co-respondent/adulteryJourney.js
  test/e2e/paths/respondent/2yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/5yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
  test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
  test/e2e/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-507
