Repository hmcts/div-respondent-frontend, pull requests merged in 2020-12, with the labels that each got.

#508 Reduce crossbrowser test timeouts
  config/default.yml
Labels: ns:divorce, prd:div, rel:div-rfe-pr-508

#509 Feature: Increase screenResolution for Windows Firefox crossbrowser tests
  test/crossbrowser/supportedBrowsers.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-509

#510 Crossbrowser improvement: Update the waitForText() value to be unique to the expected page
  test/e2e/pages/co-respondent/crRespond.step.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-510

#511 DIV-6653: Allow new states on RFE
  config/default.yml
  middleware/petitionMiddleware.js
  mocks/steps/idamLogin/IdamLogin.content.json
  test/unit/middleware/petitionMiddleware.test.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-511
