Repository hmcts/div-respondent-frontend, pull requests merged in 2021-12, with the labels that each got.

#597 DFR-701: Upgrade Redis
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-597

#598 DFR-701: Remove Redis libs from project
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-598

#599 DFR-701: Fix Redis AAT Connectivity
  charts/div-rfe/values.preview.template.yaml
  services/redis.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-599

#602 DFR-736: updated fortify release id
  test/java/config/fortify-client.properties
Labels: ns:divorce, prd:div, rel:div-rfe-pr-602

#601 Dfr 701 add redis libs
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.aat.template.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  package.json
  services/redis.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-601

#603 Dfr 701 sonar ignore redis
  sonar-project.properties
Labels: ns:divorce, prd:div, rel:div-rfe-pr-603
