Repository hmcts/div-respondent-frontend, pull requests merged in 2021-05, with the labels that each got.

#553 redis 3.1.1
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-553

#536 RPET-703: add cost details option on review page.
  package.json
  steps/co-respondent/cr-review-application/CrReviewApplication.content.json
  steps/co-respondent/cr-review-application/CrReviewApplication.html
  steps/respondent/review-application/ReviewApplication.content.json
  steps/respondent/review-application/ReviewApplication.html
  test/unit/steps/corespondent/crReviewApplication.test.js
  test/unit/steps/respondent/reviewApplication.test.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-536

#561 RPET-1014: Downgrading redis
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-561
