Repository hmcts/div-respondent-frontend, pull requests merged in 2021-04, with the labels that each got.

#545 DIV-6228: Citizen respondent co-respondent can submit AOS response whilst bailiff application in progress
  config/default.yml
  core/utils/petitionHelper.js
  middleware/petitionMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer coRespNotDefendingBailiffCase.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesCaseBailiffNotLinked.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer yesCaseDefendedBailiffStarted.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-adultery-defendedIssuedToBailiff.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-bailiffCaseNotLinked.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-coRespNotDefendingBailiffCase.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  package.json
  steps/co-respondent/cr-choose-a-response/CrChooseAResponse.step.js
  steps/respondent/choose-a-response/ChooseAResponse.step.js
  steps/respondent/progress-bar/ProgressBar.config.js
  test/e2e/pages/common/idam.step.js
  test/e2e/paths/respondent/adulteryJourney.js
  test/e2e/paths/respondent/captureCaseAndPin.js
  test/unit/core/utils/petitionerHelper.test.js
  test/unit/middleware/petitionMiddleware.test.js
  test/unit/steps/respondent/progressBar.test.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-545

#535 RPET-647 changes to replace the 2nd option 'English and Welsh' to 'We…
  steps/respondent/language-preference/LanguagePreference.content.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-535

#548 netmask, ssri, node-notifier
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-548

#551 DIV-6948: Organize RFE test repository
  .gitignore
  README.md
  config/e2e.yml
  package.json
  test/e2e/codecept.conf.js
  test/e2e/pages/respondent/financialSituation.js
  test/e2e/paths/co-respondent/adulteryJourneyAdmit-cy.js
  test/e2e/paths/co-respondent/adulteryJourneyAdmit-en-cy.js
  test/e2e/paths/co-respondent/adulteryJourneyAdmit-en.js
  test/e2e/paths/respondent/2yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/5yrSeparationHappyPath-en-cy.js
  test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
  test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
  test/mocks/codecept.mocks.js
  test/mocks/paths/co-respondent/adulteryJourneyNoAdmit.js
  test/mocks/paths/co-respondent/progressBar.js
  test/mocks/paths/errors.js
  test/mocks/paths/respondent/2yrSeparationNegativeScenarios.js
  test/mocks/paths/respondent/5yrSeparationNegativeScenarios.js
  test/mocks/paths/respondent/adulteryJourney.js
  test/mocks/paths/respondent/behaviourNegativeScenarios.js
  test/mocks/paths/respondent/captureCaseAndPin.js
  test/mocks/paths/respondent/progressBar.js
  test/mocks/paths/respondent/solicitorAddress.js
  test/mocks/paths/respondent/solicitorNominatePath.js
  test/mocks/paths/signout.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-551

#552 DIV-6948: Minor markup style update
  README.md
Labels: ns:divorce, prd:div, rel:div-rfe-pr-552
