Repository hmcts/div-respondent-frontend, pull requests merged in 2021-01, with the labels that each got.

#513 DIV-6654: Map general referral states on Petitioner and Respondent apps
  config/default.yml
  core/utils/petitionHelper.js
  middleware/petitionMiddleware.js
  middleware/redirectMiddleware.js
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer awaitingGeneralReferralPayment.mock
  mocks/services/case-orchestration/retrieve-aos-case/GET_Authorization=Bearer generalConsiderationComplete.mock
  mocks/services/case-orchestration/retrieve-aos-case/mock-awaitingGeneralReferralPayment.json
  mocks/services/case-orchestration/retrieve-aos-case/mock-co-respondent-generalConsiderationComplete.json
  mocks/steps/idamLogin/IdamLogin.content.json
  mocks/steps/idamLogin/IdamLogin.step.js
  mocks/steps/idamLogin/IdamLogin.template.html
  package.json
  steps/respondent/progress-bar/ProgressBar.config.js
  test/unit/core/utils/petitionerHelper.test.js
  test/unit/middleware/petitionMiddleware.test.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-513

#515 DIV-6654: Update to axios version
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-515

#516 DIV-6654: Map general referral states on Respondent apps
  config/default.yml
  core/utils/petitionHelper.js
  middleware/petitionMiddleware.js
  steps/divorce-application-processing/DivorceApplicationProcessing.content.json
  steps/divorce-application-processing/DivorceApplicationProcessing.html
  steps/divorce-application-processing/DivorceApplicationProcessing.step.js
  test/unit/core/utils/petitionerHelper.test.js
  test/unit/middleware/petitionMiddleware.test.js
  test/unit/steps/divorceApplicationProcessing.test.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-516

#519 DIV-6735: Fix functional tests
  test/e2e/paths/respondent/behaviourHappyPath-en-cy.js
  test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-519

#520 DIV-6735-Update variable name
  test/e2e/paths/respondent/desertionJourneyHappyPath-en-cy.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-520

#518 DIV-6731 10017-Cross Domain suppression
  audit.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-518

#522 RPET-656: nightly build update
  Jenkinsfile_CNP
  audit.json
  security.sh
Labels: ns:divorce, prd:div, rel:div-rfe-pr-522

#524 RPET-656: don't execute zap scan
  Jenkinsfile_nightly
  audit.json
  security.sh
Labels: ns:divorce, prd:div, rel:div-rfe-pr-524
