Repository hmcts/div-respondent-frontend, pull requests merged in 2022-05, with the labels that each got.

#651 Dfr 979 correct opening hours
  app.js
  assets/js/webchat.js
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.preview.template.yaml
  charts/div-rfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  middleware/getWebchatOpenHours.js
  steps/accessibility-statement/AccessibilityStatement.step.js
  steps/authenticated/Authenticated.step.js
  steps/avaya-webchat/AvayaWebchat.html
  steps/avaya-webchat/AvayaWebchat.step.js
  steps/capture-case-and-pin/CaptureCaseAndPin.step.js
  steps/co-respondent/cr-admit-adultery/CrAdmitAdultery.step.js
  steps/co-respondent/cr-agree-to-pay-costs/CrAgreeToPayCosts.step.js
  steps/co-respondent/cr-check-your-answers/CrCheckYourAnswers.step.js
  steps/co-respondent/cr-choose-a-response/CrChooseAResponse.step.js
  steps/co-respondent/cr-confirm-defence/CrConfirmDefence.step.js
  steps/co-respondent/cr-contact-details/CrContactDetails.step.js
  steps/co-respondent/cr-done/CrDone.step.js
  steps/co-respondent/cr-progress-bar/CrProgressBar.step.js
  steps/co-respondent/cr-respond/CrRespond.step.js
  steps/co-respondent/cr-review-application/CrReviewApplication.step.js
  steps/cookies-policy/CookiesPolicy.step.js
  steps/divorce-application-processing/DivorceApplicationProcessing.step.js
  steps/end/End.step.js
  steps/entry/Entry.step.js
  steps/equality/Equality.step.js
  steps/privacy-policy/PrivacyPolicy.step.js
  steps/respondent/admit-adultery/AdmitAdultery.step.js
  steps/respondent/agree-to-pay-costs/AgreeToPayCosts.step.js
  steps/respondent/check-your-answers/CheckYourAnswers.step.js
  steps/respondent/choose-a-response/ChooseAResponse.step.js
  steps/respondent/confirm-defence/ConfirmDefence.step.js
  steps/respondent/consent-decree/ConsentDecree.step.js
  steps/respondent/contact-details/ContactDetails.step.js
  steps/respondent/defend-financial-hardship/DefendFinancialHardship.step.js
  steps/respondent/done/Done.step.js
  steps/respondent/financial-situation/FinancialSituation.step.js
  steps/respondent/jurisdiction/Jurisdiction.step.js
  steps/respondent/language-preference/LanguagePreference.step.js
  steps/respondent/legal-proceedings/LegalProceedings.step.js
  steps/respondent/no-consent-are-you-sure/NoConsentAreYouSure.step.js
  steps/respondent/progress-bar/ProgressBar.step.js
  steps/respondent/respond/Respond.step.js
  steps/respondent/review-application/ReviewApplication.step.js
  steps/respondent/solicitor-address/SolicitorAddress.step.js
  steps/respondent/solicitor-details/SolicitorDetails.step.js
  steps/respondent/solicitor-representation/SolicitorRepresentation.step.js
  steps/terms-and-conditions/TermsAndConditions.step.js
  test/unit/middleware/getWebchatOpenHours.test.js
  views/includes/problem_with_this_page.html
Labels: ns:divorce, prd:div, rel:div-rfe-pr-651

#652 DFR 979 Fix missing webchat title
  steps/avaya-webchat/AvayaWebchat.html
  views/includes/problem_with_this_page.html
Labels: ns:divorce, prd:div, rel:div-rfe-pr-652

#653 DFR-1045 Update contactCenterClosed text
  assets/locale/locale_en-GB.json
Labels: ns:divorce, prd:div, rel:div-rfe-pr-653

#654 Autoscaling
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.yaml
Labels: ns:divorce, prd:div, rel:div-rfe-pr-654

#655 DFR-1086 Configure Pipelines for Additional Tests
  Jenkinsfile_CNP
  README.md
Labels: ns:divorce, prd:div, rel:div-rfe-pr-655
