Repository hmcts/div-respondent-frontend, pull requests merged in 2022-01, with the labels that each got.

#604 DFR-701: Fix Redis lib to 2.8.0
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-604

#605 DFR-701: Upgrade One Per Page library
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-605

#606 DFR-701: Remove redis libs as a dependency
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-606

#563 DFR-37 deploy cookie banner
  .eslintignore
  README.md
  app.js
  assets/js/cookiesManager.js
  assets/js/main.js
  assets/scss/_cookies.scss
  charts/div-rfe/Chart.yaml
  charts/div-rfe/values.preview.template.yaml
  charts/div-rfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yml
  steps/cookies-policy/CookiesPolicy.content.json
  steps/cookies-policy/CookiesPolicy.html
  test/unit/helpers/courtInformation.js
  test/unit/steps/respondent/respond.test.js
  views/check_your_answers.njk
  views/errors/not-found-error.html
  views/errors/server-error.html
  views/includes/cookies/button/macro.njk
  views/includes/cookies/button/template.njk
  views/includes/cookies/cookie-banner/cookie.njk
  views/includes/cookies/cookie-banner/macro.njk
  views/includes/cookies/cookie-banner/template.njk
  views/includes/cookies/cookie-manager/cookie-banner.njk
  views/includes/cookies/cookie-manager/cookie-reject-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-all-banner.njk
  views/includes/cookies/cookie-manager/cookie-success-banner.njk
  views/includes/head.html
  views/page.njk
  views/question.njk
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-rfe-pr-563

#609 fix dependency check issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-609

#613 DFR-37-Webchat-Fix
  assets/js/cookiesManager.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-rfe-pr-613

#614 Revert "fix dependency check issues"
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-rfe-pr-614

#617 Update cookiesManager.js
  assets/js/cookiesManager.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-rfe-pr-617

#618 Update server.js
  server.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-618
