Repository hmcts/div-respondent-frontend, pull requests merged in 2022-02, with the labels that each got.

#610 dfr-37-prod-cookie-domain
  assets/js/cookiesManager.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-610

#620 Update cookiesManager.js
  assets/js/cookiesManager.js
Labels: ns:divorce, prd:div, rel:div-rfe-pr-620

#615 DFR-872: Fix webchat issue
  middleware/helmet.js
  test/unit/middleware/helmet.test.js
  views/includes/head.html
Labels: ns:divorce, prd:div, rel:div-rfe-pr-615

#625 Dependency Fixes
  charts/div-rfe/Chart.yaml
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-rfe-pr-625

#627 fix dependency check
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-rfe-pr-627
